flink-aggregator {
    source {
        bootstrapServers = "localhost:29092"
        bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}
        schemaRegistryUrl = "http://localhost:8081"
        schemaRegistryUrl = ${?SCHEMA_REGISTRY_URL}
        topicImpressionEvents = "impression-events"
        topicImpressionEvents = ${?KAFKA_TOPIC_IMPRESSION_EVENTS}
        groupId = "impression-aggregator"
        groupId = ${?FLINK_GROUP_ID}
    }
    sink {
        url = "redis://localhost:6379"
        url = ${?FLINK_REDIS_URL}
        capWindowSeconds = 86400
        capWindowSeconds = ${?CAP_WINDOW_SECONDS}
        winhistoryWindowSeconds = 3600
        winhistoryWindowSeconds = ${?WINHISTORY_WINDOW_SECONDS}
    }
    checkpointIntervalMs = 30000
    checkpointIntervalMs = ${?CHECKPOINT_INTERVAL_MS}
    windowSeconds = 10
    windowSeconds = ${?WINDOW_SECONDS}
    allowedLatenessSeconds = 2
    allowedLatenessSeconds = ${?ALLOWED_LATENESS_SECONDS}
}
