frequency {
    server {
        port = 9090
        port = ${?FREQ_SERVICE_PORT}
    }
    redis {
        url = "redis://localhost:6379"
        url = ${?FREQ_REDIS_URL}
    }
    metrics {
        enabled = true
        enabled = ${?METRICS_ENABLED}
        port = 9091
        port = ${?METRICS_PORT}
        commonTags {
            service = "frequency-service"
            env = "local"
            env = ${?METRICS_ENV}
        }
    }
    tracing {
        enabled = true
        enabled = ${?TRACING_ENABLED}
        serviceName = "frequency-service"
        serviceName = ${?OTEL_SERVICE_NAME}
        otlpEndpoint = "http://localhost:4317"
        otlpEndpoint = ${?OTEL_EXPORTER_OTLP_ENDPOINT}
    }
}
